/**
 * CID-10 — subset ampliado dos códigos mais comuns em atenção primária e ambulatorial.
 *
 * Cobertura ~400 entradas cobrindo os capítulos principais. Para CID-10
 * exaustivo (~14k entradas), copie do DataSUS:
 * http://www2.datasus.gov.br/cid10/V2008/cid10.htm
 *
 * Mantenha o shape { code, description } — o componente CidAutocomplete
 * lida com qualquer tamanho. Texto livre também é permitido.
 */
export interface CidEntry {
  code: string;
  description: string;
}

export const CID10: CidEntry[] = [
  // A00-B99 — Doenças infecciosas e parasitárias
  { code: "A00", description: "Cólera" },
  { code: "A01.0", description: "Febre tifoide" },
  { code: "A02.0", description: "Enterite por Salmonella" },
  { code: "A04.9", description: "Infecção intestinal bacteriana não especificada" },
  { code: "A08.4", description: "Infecção intestinal viral não especificada" },
  { code: "A09", description: "Diarreia e gastroenterite de origem infecciosa" },
  { code: "A15.0", description: "Tuberculose pulmonar com confirmação bacteriológica" },
  { code: "A15.3", description: "Tuberculose pulmonar com confirmação histológica" },
  { code: "A41.9", description: "Septicemia não especificada" },
  { code: "A46", description: "Erisipela" },
  { code: "A49.9", description: "Infecção bacteriana não especificada" },
  { code: "A54.0", description: "Infecção gonocócica do trato genital inferior" },
  { code: "A56.0", description: "Infecção por clamídia do trato genital inferior" },
  { code: "A60.0", description: "Infecção genital por herpes simples" },
  { code: "A63.0", description: "Verrugas anogenitais (HPV)" },
  { code: "A87.9", description: "Meningite viral não especificada" },
  { code: "B00.1", description: "Herpes labial" },
  { code: "B01.9", description: "Varicela sem complicações" },
  { code: "B02.9", description: "Herpes zoster sem complicações" },
  { code: "B05.9", description: "Sarampo sem complicações" },
  { code: "B06.9", description: "Rubéola sem complicações" },
  { code: "B07", description: "Verrugas virais (Verrucas)" },
  { code: "B08.4", description: "Estomatite vesicular enteroviral com exantema" },
  { code: "B15.9", description: "Hepatite A aguda sem coma hepático" },
  { code: "B16.9", description: "Hepatite B aguda sem agente delta" },
  { code: "B17.1", description: "Hepatite C aguda" },
  { code: "B18.2", description: "Hepatite C crônica" },
  { code: "B19.9", description: "Hepatite viral não especificada" },
  { code: "B20", description: "Doença pelo HIV resultando em doenças infecciosas" },
  { code: "B24", description: "Doença pelo HIV não especificada" },
  { code: "B26.9", description: "Caxumba sem complicação" },
  { code: "B34.9", description: "Infecção viral não especificada" },
  { code: "B35.2", description: "Tinea das mãos" },
  { code: "B35.4", description: "Tinea do corpo" },
  { code: "B35.6", description: "Tinea cruris (jock itch)" },
  { code: "B36.0", description: "Pitiríase versicolor" },
  { code: "B37.0", description: "Candidíase da boca" },
  { code: "B37.3", description: "Candidíase da vulva e da vagina" },
  { code: "B54", description: "Malária não especificada" },
  { code: "B86", description: "Escabiose" },
  { code: "B87.9", description: "Miíase não especificada" },

  // C00-D48 — Neoplasias (selecionadas)
  { code: "C16.9", description: "Neoplasia maligna do estômago" },
  { code: "C18.9", description: "Neoplasia maligna do cólon" },
  { code: "C20", description: "Neoplasia maligna do reto" },
  { code: "C25.9", description: "Neoplasia maligna do pâncreas" },
  { code: "C34.9", description: "Neoplasia maligna dos brônquios e pulmões" },
  { code: "C50.9", description: "Neoplasia maligna da mama" },
  { code: "C53.9", description: "Neoplasia maligna do colo do útero" },
  { code: "C61", description: "Neoplasia maligna da próstata" },
  { code: "C73", description: "Neoplasia maligna da glândula tireoide" },
  { code: "C80", description: "Neoplasia maligna sem especificação de localização" },
  { code: "D17.9", description: "Lipoma não especificado" },
  { code: "D22.9", description: "Nevo melanocítico não especificado" },
  { code: "D24", description: "Neoplasia benigna da mama" },
  { code: "D25.9", description: "Leiomioma do útero não especificado" },
  { code: "D27", description: "Neoplasia benigna do ovário" },
  { code: "D32.9", description: "Neoplasia benigna das meninges" },
  { code: "D34", description: "Neoplasia benigna da glândula tireoide" },
  { code: "D36.9", description: "Neoplasia benigna sem especificação" },

  // D50-D89 — Sangue e órgãos hematopoiéticos
  { code: "D50.0", description: "Anemia por deficiência de ferro secundária a perda" },
  { code: "D50.9", description: "Anemia por deficiência de ferro não especificada" },
  { code: "D51.0", description: "Anemia por deficiência de vitamina B12" },
  { code: "D52.9", description: "Anemia por deficiência de folato" },
  { code: "D53.9", description: "Anemia nutricional não especificada" },
  { code: "D56.1", description: "Beta talassemia" },
  { code: "D57.1", description: "Anemia falciforme sem crise" },
  { code: "D64.9", description: "Anemia não especificada" },
  { code: "D68.9", description: "Defeito da coagulação não especificado" },
  { code: "D69.6", description: "Trombocitopenia não especificada" },

  // E00-E90 — Endócrinas, nutricionais e metabólicas
  { code: "E03.9", description: "Hipotireoidismo não especificado" },
  { code: "E04.9", description: "Bócio não tóxico não especificado" },
  { code: "E05.0", description: "Hipertireoidismo com bócio difuso" },
  { code: "E05.9", description: "Hipertireoidismo não especificado" },
  { code: "E06.3", description: "Tireoidite autoimune (Hashimoto)" },
  { code: "E07.9", description: "Distúrbio da glândula tireoide não especificado" },
  { code: "E10.9", description: "Diabetes mellitus tipo 1 sem complicações" },
  { code: "E11.9", description: "Diabetes mellitus tipo 2 sem complicações" },
  { code: "E11.40", description: "DM tipo 2 com neuropatia diabética não especificada" },
  { code: "E11.65", description: "Diabetes tipo 2 com hiperglicemia" },
  { code: "E11.21", description: "DM tipo 2 com nefropatia diabética" },
  { code: "E14.9", description: "Diabetes mellitus não especificado" },
  { code: "E16.2", description: "Hipoglicemia não especificada" },
  { code: "E22.1", description: "Hiperprolactinemia" },
  { code: "E27.4", description: "Outras insuficiências adrenocorticais" },
  { code: "E55.9", description: "Deficiência de vitamina D não especificada" },
  { code: "E63.9", description: "Deficiência nutricional não especificada" },
  { code: "E66.0", description: "Obesidade devida a excesso de calorias" },
  { code: "E66.2", description: "Obesidade extrema com hipoventilação alveolar" },
  { code: "E66.9", description: "Obesidade não especificada" },
  { code: "E73.9", description: "Intolerância à lactose não especificada" },
  { code: "E78.0", description: "Hipercolesterolemia pura" },
  { code: "E78.1", description: "Hipertrigliceridemia pura" },
  { code: "E78.2", description: "Hiperlipidemia mista" },
  { code: "E78.5", description: "Dislipidemia não especificada" },
  { code: "E79.0", description: "Hiperuricemia sem sinais de artrite" },
  { code: "E83.5", description: "Distúrbios do metabolismo do cálcio" },
  { code: "E86", description: "Depleção de volume (desidratação)" },
  { code: "E87.6", description: "Hipocalemia" },

  // F00-F99 — Transtornos mentais e comportamentais
  { code: "F03", description: "Demência não especificada" },
  { code: "F10.2", description: "Transtornos por uso de álcool (dependência)" },
  { code: "F11.2", description: "Transtornos por uso de opioides (dependência)" },
  { code: "F17.2", description: "Dependência de tabaco" },
  { code: "F19.2", description: "Transtornos por uso de múltiplas drogas" },
  { code: "F20.9", description: "Esquizofrenia não especificada" },
  { code: "F25.0", description: "Transtorno esquizoafetivo tipo maníaco" },
  { code: "F31.0", description: "Transtorno afetivo bipolar episódio maníaco" },
  { code: "F31.4", description: "TAB episódio depressivo grave sem psicose" },
  { code: "F31.9", description: "Transtorno afetivo bipolar não especificado" },
  { code: "F32.0", description: "Episódio depressivo leve" },
  { code: "F32.1", description: "Episódio depressivo moderado" },
  { code: "F32.2", description: "Episódio depressivo grave sem sintomas psicóticos" },
  { code: "F32.9", description: "Episódio depressivo não especificado" },
  { code: "F33.0", description: "Transtorno depressivo recorrente leve" },
  { code: "F33.1", description: "Transtorno depressivo recorrente moderado" },
  { code: "F33.9", description: "Transtorno depressivo recorrente não especificado" },
  { code: "F40.0", description: "Agorafobia" },
  { code: "F40.1", description: "Fobias sociais" },
  { code: "F41.0", description: "Transtorno de pânico" },
  { code: "F41.1", description: "Transtorno de ansiedade generalizada" },
  { code: "F41.2", description: "Transtorno misto ansioso e depressivo" },
  { code: "F42.9", description: "Transtorno obsessivo-compulsivo não especificado" },
  { code: "F43.0", description: "Reação aguda ao estresse" },
  { code: "F43.1", description: "Transtorno de estresse pós-traumático" },
  { code: "F43.2", description: "Transtornos de adaptação" },
  { code: "F44.9", description: "Transtorno dissociativo não especificado" },
  { code: "F45.0", description: "Transtorno de somatização" },
  { code: "F45.2", description: "Transtorno hipocondríaco" },
  { code: "F45.9", description: "Transtorno somatoforme não especificado" },
  { code: "F50.0", description: "Anorexia nervosa" },
  { code: "F50.2", description: "Bulimia nervosa" },
  { code: "F51.0", description: "Insônia não orgânica" },
  { code: "F60.3", description: "Transtorno de personalidade borderline" },
  { code: "F60.9", description: "Transtorno de personalidade não especificado" },
  { code: "F70.9", description: "Retardo mental leve" },
  { code: "F84.0", description: "Autismo infantil" },
  { code: "F84.5", description: "Síndrome de Asperger" },
  { code: "F90.0", description: "Distúrbios de atividade e atenção (TDAH)" },
  { code: "F90.9", description: "Transtorno hipercinético não especificado" },

  // G00-G99 — Sistema nervoso
  { code: "G20", description: "Doença de Parkinson" },
  { code: "G35", description: "Esclerose múltipla" },
  { code: "G40.0", description: "Epilepsia focal idiopática" },
  { code: "G40.3", description: "Epilepsia generalizada idiopática" },
  { code: "G40.9", description: "Epilepsia não especificada" },
  { code: "G43.0", description: "Enxaqueca sem aura" },
  { code: "G43.1", description: "Enxaqueca com aura" },
  { code: "G43.9", description: "Enxaqueca não especificada" },
  { code: "G44.0", description: "Cefaleia em salvas" },
  { code: "G44.2", description: "Cefaleia tensional" },
  { code: "G45.9", description: "Acidente isquêmico transitório não especificado" },
  { code: "G47.0", description: "Distúrbios do início e manutenção do sono (insônia)" },
  { code: "G47.1", description: "Distúrbios da sonolência excessiva (hipersonolência)" },
  { code: "G47.3", description: "Apneia do sono" },
  { code: "G50.0", description: "Nevralgia do trigêmeo" },
  { code: "G54.4", description: "Distúrbios das raízes nervosas lombossacrais" },
  { code: "G56.0", description: "Síndrome do túnel do carpo" },
  { code: "G56.3", description: "Lesão do nervo radial" },
  { code: "G57.6", description: "Lesão do nervo plantar" },
  { code: "G62.9", description: "Polineuropatia não especificada" },
  { code: "G70.0", description: "Miastenia gravis" },

  // H00-H59 — Olhos
  { code: "H00.0", description: "Hordéolo" },
  { code: "H01.0", description: "Blefarite" },
  { code: "H02.4", description: "Ptose palpebral" },
  { code: "H04.1", description: "Outros distúrbios do aparelho lacrimal" },
  { code: "H10.1", description: "Conjuntivite atópica aguda" },
  { code: "H10.4", description: "Conjuntivite crônica" },
  { code: "H10.9", description: "Conjuntivite não especificada" },
  { code: "H25.9", description: "Catarata senil não especificada" },
  { code: "H35.0", description: "Retinopatia de fundo e alterações vasculares" },
  { code: "H40.0", description: "Suspeita de glaucoma" },
  { code: "H40.9", description: "Glaucoma não especificado" },
  { code: "H52.0", description: "Hipermetropia" },
  { code: "H52.1", description: "Miopia" },
  { code: "H52.2", description: "Astigmatismo" },
  { code: "H52.4", description: "Presbiopia" },
  { code: "H53.2", description: "Diplopia" },
  { code: "H57.1", description: "Dor ocular" },

  // H60-H95 — Ouvido
  { code: "H60.9", description: "Otite externa não especificada" },
  { code: "H61.2", description: "Cerume impactado" },
  { code: "H65.9", description: "Otite média não supurativa não especificada" },
  { code: "H66.0", description: "Otite média supurativa aguda" },
  { code: "H66.9", description: "Otite média não especificada" },
  { code: "H81.0", description: "Doença de Ménière" },
  { code: "H81.1", description: "Vertigem paroxística benigna" },
  { code: "H81.4", description: "Vertigem de origem central" },
  { code: "H90.3", description: "Perda de audição neurossensorial bilateral" },
  { code: "H91.9", description: "Perda de audição não especificada" },
  { code: "H92.0", description: "Otalgia" },
  { code: "H93.1", description: "Tinido (zumbido)" },

  // I00-I99 — Sistema circulatório
  { code: "I10", description: "Hipertensão essencial (primária)" },
  { code: "I11.0", description: "Doença cardíaca hipertensiva com insuficiência cardíaca" },
  { code: "I11.9", description: "Doença cardíaca hipertensiva sem insuficiência" },
  { code: "I12.9", description: "Doença renal hipertensiva sem insuficiência" },
  { code: "I15.9", description: "Hipertensão secundária não especificada" },
  { code: "I20.0", description: "Angina instável" },
  { code: "I20.9", description: "Angina pectoris não especificada" },
  { code: "I21.9", description: "Infarto agudo do miocárdio não especificado" },
  { code: "I25.0", description: "Doença cardiovascular aterosclerótica" },
  { code: "I25.1", description: "Doença aterosclerótica do coração" },
  { code: "I25.9", description: "Doença isquêmica crônica do coração não esp." },
  { code: "I34.0", description: "Insuficiência mitral" },
  { code: "I42.0", description: "Cardiomiopatia dilatada" },
  { code: "I48", description: "Fibrilação e flutter atrial" },
  { code: "I49.5", description: "Síndrome do nó sinusal doente" },
  { code: "I49.9", description: "Arritmia cardíaca não especificada" },
  { code: "I50.0", description: "Insuficiência cardíaca congestiva" },
  { code: "I50.1", description: "Insuficiência ventricular esquerda" },
  { code: "I50.9", description: "Insuficiência cardíaca não especificada" },
  { code: "I63.9", description: "Infarto cerebral não especificado" },
  { code: "I64", description: "Acidente vascular cerebral não especificado" },
  { code: "I65.2", description: "Oclusão e estenose da artéria carótida" },
  { code: "I70.2", description: "Aterosclerose das artérias das extremidades" },
  { code: "I73.9", description: "Doença vascular periférica não especificada" },
  { code: "I80.2", description: "Trombose venosa profunda de MMII" },
  { code: "I83.0", description: "Varizes dos MMII com úlcera" },
  { code: "I83.9", description: "Varizes dos MMII sem úlcera ou inflamação" },
  { code: "I84.9", description: "Hemorroidas não especificadas sem complicação" },
  { code: "I87.2", description: "Insuficiência venosa crônica (periférica)" },
  { code: "I95.9", description: "Hipotensão não especificada" },

  // J00-J99 — Respiratório
  { code: "J00", description: "Nasofaringite aguda (resfriado comum)" },
  { code: "J01.9", description: "Sinusite aguda não especificada" },
  { code: "J02.0", description: "Faringite estreptocócica" },
  { code: "J02.9", description: "Faringite aguda não especificada" },
  { code: "J03.9", description: "Amigdalite aguda não especificada" },
  { code: "J04.0", description: "Laringite aguda" },
  { code: "J06.9", description: "Infecção aguda das vias aéreas superiores" },
  { code: "J11.1", description: "Influenza com outras manifestações respiratórias" },
  { code: "J15.9", description: "Pneumonia bacteriana não especificada" },
  { code: "J18.0", description: "Broncopneumonia não especificada" },
  { code: "J18.9", description: "Pneumonia não especificada" },
  { code: "J20.9", description: "Bronquite aguda não especificada" },
  { code: "J21.9", description: "Bronquiolite aguda não especificada" },
  { code: "J22", description: "Infecção aguda não especificada das vias aéreas" },
  { code: "J30.1", description: "Rinite alérgica devida ao pólen" },
  { code: "J30.4", description: "Rinite alérgica não especificada" },
  { code: "J31.0", description: "Rinite crônica" },
  { code: "J32.0", description: "Sinusite maxilar crônica" },
  { code: "J32.9", description: "Sinusite crônica não especificada" },
  { code: "J35.1", description: "Hipertrofia das amígdalas" },
  { code: "J42", description: "Bronquite crônica não especificada" },
  { code: "J43.9", description: "Enfisema pulmonar não especificado" },
  { code: "J44.0", description: "DPOC com infecção respiratória aguda" },
  { code: "J44.1", description: "DPOC com exacerbação aguda" },
  { code: "J44.9", description: "DPOC não especificada" },
  { code: "J45.0", description: "Asma predominantemente alérgica" },
  { code: "J45.9", description: "Asma não especificada" },
  { code: "J46", description: "Estado de mal asmático" },
  { code: "J81", description: "Edema pulmonar" },
  { code: "J84.9", description: "Doença pulmonar intersticial não especificada" },
  { code: "J90", description: "Derrame pleural não classificado em outra parte" },
  { code: "J96.9", description: "Insuficiência respiratória não especificada" },
  { code: "J98.4", description: "Outros transtornos do pulmão" },

  // K00-K93 — Digestivo
  { code: "K02.9", description: "Cárie dentária não especificada" },
  { code: "K05.6", description: "Doença periodontal não especificada" },
  { code: "K11.7", description: "Distúrbios da secreção salivar" },
  { code: "K12.0", description: "Estomatite aftosa recorrente" },
  { code: "K20", description: "Esofagite" },
  { code: "K21.0", description: "DRGE com esofagite" },
  { code: "K21.9", description: "DRGE sem esofagite" },
  { code: "K22.0", description: "Acalásia do cárdia" },
  { code: "K25.9", description: "Úlcera gástrica não especificada" },
  { code: "K26.9", description: "Úlcera duodenal não especificada" },
  { code: "K27.9", description: "Úlcera péptica não especificada" },
  { code: "K29.1", description: "Outras gastrites agudas" },
  { code: "K29.5", description: "Gastrite crônica não especificada" },
  { code: "K29.7", description: "Gastrite não especificada" },
  { code: "K30", description: "Dispepsia" },
  { code: "K35.8", description: "Apendicite aguda não especificada" },
  { code: "K40.9", description: "Hérnia inguinal unilateral sem obstrução" },
  { code: "K42.9", description: "Hérnia umbilical sem obstrução" },
  { code: "K44.9", description: "Hérnia diafragmática sem obstrução" },
  { code: "K50.9", description: "Doença de Crohn não especificada" },
  { code: "K51.9", description: "Colite ulcerativa não especificada" },
  { code: "K52.9", description: "Gastroenterite e colite não infecciosas" },
  { code: "K57.3", description: "Doença diverticular do intestino grosso" },
  { code: "K58.9", description: "Síndrome do intestino irritável" },
  { code: "K59.0", description: "Constipação" },
  { code: "K59.1", description: "Diarreia funcional" },
  { code: "K62.5", description: "Hemorragia do ânus e do reto" },
  { code: "K63.5", description: "Pólipo do cólon" },
  { code: "K70.0", description: "Doença hepática alcoólica - fígado gorduroso" },
  { code: "K70.3", description: "Cirrose hepática alcoólica" },
  { code: "K74.6", description: "Cirrose hepática outra e não especificada" },
  { code: "K75.9", description: "Doença inflamatória do fígado não especificada" },
  { code: "K76.0", description: "Esteatose hepática não classificada" },
  { code: "K80.2", description: "Cálculo da vesícula biliar sem colecistite" },
  { code: "K81.0", description: "Colecistite aguda" },
  { code: "K85.9", description: "Pancreatite aguda não especificada" },
  { code: "K86.1", description: "Pancreatite crônica não especificada" },
  { code: "K90.0", description: "Doença celíaca" },
  { code: "K92.2", description: "Hemorragia gastrointestinal não especificada" },

  // L00-L99 — Pele
  { code: "L02.9", description: "Abscesso cutâneo, furúnculo e antraz não esp." },
  { code: "L03.9", description: "Celulite não especificada" },
  { code: "L08.9", description: "Infecção local da pele não especificada" },
  { code: "L20.9", description: "Dermatite atópica não especificada" },
  { code: "L21.0", description: "Seborreia capitis" },
  { code: "L21.9", description: "Dermatite seborreica não especificada" },
  { code: "L23.9", description: "Dermatite alérgica de contato" },
  { code: "L24.9", description: "Dermatite de contato por irritante" },
  { code: "L25.9", description: "Dermatite de contato não especificada" },
  { code: "L27.0", description: "Erupção cutânea generalizada por medicamento" },
  { code: "L29.9", description: "Prurido não especificado" },
  { code: "L30.4", description: "Eritema intertrigo" },
  { code: "L30.9", description: "Dermatite não especificada" },
  { code: "L40.0", description: "Psoríase vulgar" },
  { code: "L40.9", description: "Psoríase não especificada" },
  { code: "L50.0", description: "Urticária alérgica" },
  { code: "L50.9", description: "Urticária não especificada" },
  { code: "L57.0", description: "Ceratose actínica" },
  { code: "L70.0", description: "Acne vulgar" },
  { code: "L71.9", description: "Rosácea não especificada" },
  { code: "L72.1", description: "Cisto sebáceo" },
  { code: "L73.0", description: "Acne queloide" },
  { code: "L80", description: "Vitiligo" },
  { code: "L81.4", description: "Pigmentação melanodérmica" },
  { code: "L82", description: "Ceratose seborreica" },
  { code: "L85.3", description: "Xerose cutânea" },
  { code: "L91.0", description: "Cicatriz queloide" },
  { code: "L98.0", description: "Granuloma piogênico" },
  { code: "L98.9", description: "Afecção da pele e tecido subcutâneo não esp." },

  // M00-M99 — Musculoesquelético
  { code: "M05.9", description: "Artrite reumatoide soropositiva não especificada" },
  { code: "M06.9", description: "Artrite reumatoide não especificada" },
  { code: "M10.0", description: "Gota idiopática" },
  { code: "M10.9", description: "Gota não especificada" },
  { code: "M13.9", description: "Artrite não especificada" },
  { code: "M15.0", description: "Osteoartrose primária generalizada" },
  { code: "M16.9", description: "Coxartrose não especificada" },
  { code: "M17.9", description: "Gonartrose não especificada" },
  { code: "M19.0", description: "Artrose primária de outras articulações" },
  { code: "M19.9", description: "Artrose não especificada" },
  { code: "M20.1", description: "Hálux valgo (joanete)" },
  { code: "M23.5", description: "Instabilidade crônica do joelho" },
  { code: "M25.5", description: "Dor articular" },
  { code: "M25.6", description: "Rigidez articular não classificada" },
  { code: "M32.9", description: "Lúpus eritematoso sistêmico não especificado" },
  { code: "M35.0", description: "Síndrome seca (Sjögren)" },
  { code: "M40.0", description: "Cifose postural" },
  { code: "M41.9", description: "Escoliose não especificada" },
  { code: "M47.9", description: "Espondilose não especificada" },
  { code: "M50.1", description: "Transtorno de disco cervical com radiculopatia" },
  { code: "M51.1", description: "Hérnia de disco lombar com radiculopatia" },
  { code: "M53.1", description: "Síndrome cervicobraquial" },
  { code: "M54.2", description: "Cervicalgia" },
  { code: "M54.3", description: "Ciática" },
  { code: "M54.4", description: "Lumbago com ciática" },
  { code: "M54.5", description: "Dor lombar baixa" },
  { code: "M54.6", description: "Dor na coluna torácica" },
  { code: "M54.9", description: "Dorsalgia não especificada" },
  { code: "M60.9", description: "Miosite não especificada" },
  { code: "M62.6", description: "Distensão muscular" },
  { code: "M65.3", description: "Dedo em gatilho" },
  { code: "M65.4", description: "Tenossinovite estiloide radial (de Quervain)" },
  { code: "M65.9", description: "Sinovite e tenossinovite não especificadas" },
  { code: "M70.0", description: "Sinovite crepitante crônica da mão e do punho" },
  { code: "M72.2", description: "Fascite plantar" },
  { code: "M75.0", description: "Capsulite adesiva do ombro" },
  { code: "M75.1", description: "Síndrome do manguito rotador" },
  { code: "M77.1", description: "Epicondilite lateral (cotovelo de tenista)" },
  { code: "M77.4", description: "Metatarsalgia" },
  { code: "M79.0", description: "Reumatismo não especificado" },
  { code: "M79.1", description: "Mialgia" },
  { code: "M79.6", description: "Dor em membro" },
  { code: "M79.7", description: "Fibromialgia" },
  { code: "M81.0", description: "Osteoporose pós-menopáusica" },
  { code: "M81.9", description: "Osteoporose não especificada" },
  { code: "M85.9", description: "Distúrbio da densidade óssea não especificado" },
  { code: "M89.9", description: "Doença óssea não especificada" },

  // N00-N99 — Geniturinário
  { code: "N10", description: "Nefrite tubulointersticial aguda" },
  { code: "N11.9", description: "Nefrite tubulointersticial crônica não especificada" },
  { code: "N18.3", description: "Doença renal crônica estágio 3" },
  { code: "N18.4", description: "Doença renal crônica estágio 4" },
  { code: "N18.5", description: "Doença renal crônica estágio 5" },
  { code: "N18.9", description: "Doença renal crônica não especificada" },
  { code: "N19", description: "Insuficiência renal não especificada" },
  { code: "N20.0", description: "Cálculo do rim" },
  { code: "N20.1", description: "Cálculo do ureter" },
  { code: "N28.9", description: "Distúrbio do rim e ureter não especificado" },
  { code: "N30.0", description: "Cistite aguda" },
  { code: "N30.9", description: "Cistite não especificada" },
  { code: "N34.2", description: "Outras uretrites" },
  { code: "N39.0", description: "Infecção do trato urinário, local não esp." },
  { code: "N39.3", description: "Incontinência urinária de esforço" },
  { code: "N40", description: "Hiperplasia prostática" },
  { code: "N41.0", description: "Prostatite aguda" },
  { code: "N41.1", description: "Prostatite crônica" },
  { code: "N45.9", description: "Orquite e epididimite sem abscesso" },
  { code: "N48.4", description: "Disfunção erétil" },
  { code: "N60.1", description: "Mastopatia cística difusa" },
  { code: "N61", description: "Distúrbios inflamatórios da mama" },
  { code: "N63", description: "Nódulo mamário não especificado" },
  { code: "N64.4", description: "Mastodinia" },
  { code: "N70.9", description: "Salpingite e ooforite não especificadas" },
  { code: "N72", description: "Doença inflamatória do colo do útero" },
  { code: "N73.9", description: "Doença inflamatória pélvica feminina" },
  { code: "N76.0", description: "Vaginite aguda" },
  { code: "N81.1", description: "Cistocele" },
  { code: "N84.0", description: "Pólipo do corpo do útero" },
  { code: "N85.0", description: "Hiperplasia endometrial" },
  { code: "N87.9", description: "Displasia do colo do útero não especificada" },
  { code: "N91.2", description: "Amenorreia não especificada" },
  { code: "N92.0", description: "Menstruação excessiva ou frequente" },
  { code: "N92.1", description: "Menstruação excessiva e frequente" },
  { code: "N92.6", description: "Menstruação irregular não especificada" },
  { code: "N93.9", description: "Sangramento uterino anormal não especificado" },
  { code: "N94.4", description: "Dismenorreia primária" },
  { code: "N94.6", description: "Dismenorreia não especificada" },
  { code: "N95.0", description: "Sangramento pós-menopausa" },
  { code: "N95.1", description: "Estados menopáusicos e climatéricos femininos" },
  { code: "N97.9", description: "Esterilidade feminina não especificada" },

  // O00-O99 — Gravidez, parto e puerpério
  { code: "O00.9", description: "Gravidez ectópica não especificada" },
  { code: "O03.9", description: "Aborto espontâneo completo" },
  { code: "O09.9", description: "Supervisão de gravidez normal" },
  { code: "O10.0", description: "Hipertensão essencial pré-existente complicando" },
  { code: "O13", description: "Hipertensão gestacional sem proteinúria" },
  { code: "O14.9", description: "Pré-eclâmpsia não especificada" },
  { code: "O20.0", description: "Aborto evitado" },
  { code: "O21.0", description: "Hiperêmese gravídica leve" },
  { code: "O21.9", description: "Vômitos da gravidez não especificados" },
  { code: "O23.4", description: "Infecção urinária não especificada na gravidez" },
  { code: "O24.4", description: "Diabetes mellitus gestacional" },
  { code: "O36.5", description: "Assistência prestada à mãe por crescimento insuf." },
  { code: "O80", description: "Parto único espontâneo" },
  { code: "O85", description: "Infecção puerperal" },
  { code: "O90.4", description: "Insuficiência renal aguda pós-parto" },

  // R00-R99 — Sintomas, sinais e achados anormais
  { code: "R00.0", description: "Taquicardia não especificada" },
  { code: "R00.2", description: "Palpitações" },
  { code: "R05", description: "Tosse" },
  { code: "R06.0", description: "Dispneia" },
  { code: "R06.2", description: "Sibilância" },
  { code: "R07.0", description: "Dor de garganta" },
  { code: "R07.4", description: "Dor torácica não especificada" },
  { code: "R10.1", description: "Dor localizada no abdome superior" },
  { code: "R10.2", description: "Dor pélvica e perineal" },
  { code: "R10.3", description: "Dor localizada no abdome inferior" },
  { code: "R10.4", description: "Dor abdominal não especificada" },
  { code: "R11", description: "Náusea e vômitos" },
  { code: "R13", description: "Disfagia" },
  { code: "R14", description: "Flatulência e afecções correlatas" },
  { code: "R17", description: "Icterícia não especificada" },
  { code: "R19.7", description: "Diarreia não especificada" },
  { code: "R20.2", description: "Parestesia da pele" },
  { code: "R21", description: "Eritema e outras erupções cutâneas" },
  { code: "R22.9", description: "Tumefação localizada da pele" },
  { code: "R30.0", description: "Disúria" },
  { code: "R31", description: "Hematúria não especificada" },
  { code: "R32", description: "Incontinência urinária não especificada" },
  { code: "R33", description: "Retenção urinária" },
  { code: "R35", description: "Poliúria" },
  { code: "R40.0", description: "Sonolência" },
  { code: "R41.0", description: "Desorientação não especificada" },
  { code: "R42", description: "Tontura e instabilidade" },
  { code: "R45.0", description: "Nervosismo" },
  { code: "R45.1", description: "Inquietação e agitação" },
  { code: "R45.4", description: "Irritabilidade" },
  { code: "R50.9", description: "Febre não especificada" },
  { code: "R51", description: "Cefaleia" },
  { code: "R52.2", description: "Outras dores crônicas" },
  { code: "R53", description: "Mal-estar e fadiga" },
  { code: "R55", description: "Síncope e colapso" },
  { code: "R56.8", description: "Outras convulsões não classificadas" },
  { code: "R60.0", description: "Edema localizado" },
  { code: "R60.9", description: "Edema não especificado" },
  { code: "R63.0", description: "Anorexia" },
  { code: "R63.4", description: "Perda anormal de peso" },
  { code: "R63.5", description: "Ganho anormal de peso" },
  { code: "R73.0", description: "Anormalidades do teste de tolerância à glicose" },
  { code: "R73.9", description: "Hiperglicemia não especificada" },
  { code: "R74.0", description: "Elevação de transaminases" },
  { code: "R94.3", description: "Achados anormais em exame da função cardiovascular" },

  // S00-T98 — Lesões e traumatismos (selecionados)
  { code: "S00.9", description: "Traumatismo superficial da cabeça não especificado" },
  { code: "S06.0", description: "Concussão" },
  { code: "S13.4", description: "Entorse e distensão da coluna cervical" },
  { code: "S33.5", description: "Entorse e distensão da coluna lombar" },
  { code: "S43.0", description: "Luxação da articulação do ombro" },
  { code: "S52.5", description: "Fratura da extremidade distal do rádio" },
  { code: "S62.6", description: "Fratura de outros dedos da mão" },
  { code: "S82.6", description: "Fratura do maléolo lateral" },
  { code: "S83.5", description: "Entorse e distensão do joelho" },
  { code: "S93.4", description: "Entorse e distensão do tornozelo" },
  { code: "T14.9", description: "Lesão não especificada" },

  // Z00-Z99 — Fatores de saúde e contatos com serviços
  { code: "Z00.0", description: "Exame médico geral" },
  { code: "Z00.1", description: "Exame de rotina da saúde da criança" },
  { code: "Z01.4", description: "Exame ginecológico de rotina" },
  { code: "Z11.3", description: "Rastreamento de infecções sexualmente transmissíveis" },
  { code: "Z12.4", description: "Rastreamento de câncer do colo do útero" },
  { code: "Z12.5", description: "Rastreamento de câncer da próstata" },
  { code: "Z13.1", description: "Rastreamento de diabetes mellitus" },
  { code: "Z23.9", description: "Vacinação contra doença bacteriana não esp." },
  { code: "Z25.1", description: "Vacinação contra influenza" },
  { code: "Z30.0", description: "Aconselhamento contraceptivo geral" },
  { code: "Z30.9", description: "Anticoncepção não especificada" },
  { code: "Z33", description: "Gravidez como achado casual" },
  { code: "Z34.9", description: "Supervisão de gravidez normal não especificada" },
  { code: "Z51.0", description: "Sessão de radioterapia" },
  { code: "Z51.1", description: "Sessão de quimioterapia" },
  { code: "Z71.1", description: "Pessoa com queixa em quem nenhum diagnóstico é feito" },
  { code: "Z71.3", description: "Aconselhamento dietético" },
  { code: "Z71.4", description: "Aconselhamento e supervisão de alcoolismo" },
  { code: "Z71.6", description: "Aconselhamento e supervisão de tabagismo" },
  { code: "Z76.5", description: "Pessoa que simula doença" },
  { code: "Z80", description: "História familiar de neoplasia maligna" },
  { code: "Z82.4", description: "História familiar de doenças isquêmicas do coração" },
  { code: "Z86.4", description: "História pessoal de abuso de substâncias psicoativas" },
];
