/**
 * RENAME — Relação Nacional de Medicamentos Essenciais (subset ampliado).
 *
 * ~200 medicamentos. A RENAME oficial tem ~900 itens. Para expandir:
 * https://www.gov.br/saude/pt-br/composicao/sctie/daf/rename
 *
 * Mantenha o shape { name } — o componente DrugAutocomplete lida com
 * qualquer tamanho. Texto livre também é permitido.
 */
export interface DrugEntry {
  name: string;
}

const NAMES: string[] = [
  // Analgésicos / antitérmicos
  "Dipirona sódica 500 mg",
  "Dipirona sódica 1 g/2 mL",
  "Paracetamol 500 mg",
  "Paracetamol 750 mg",
  "Paracetamol gotas 200 mg/mL",
  "Ácido acetilsalicílico 100 mg",
  "Ácido acetilsalicílico 500 mg",
  "Tramadol 50 mg",
  "Tramadol 100 mg",
  "Codeína 30 mg",
  "Codeína + paracetamol 30/500 mg",
  "Morfina sulfato 10 mg",
  "Morfina LC 30 mg",

  // AINEs
  "Ibuprofeno 400 mg",
  "Ibuprofeno 600 mg",
  "Ibuprofeno suspensão 50 mg/mL",
  "Naproxeno 250 mg",
  "Naproxeno 500 mg",
  "Diclofenaco sódico 50 mg",
  "Diclofenaco potássico 50 mg",
  "Diclofenaco resinato suspensão",
  "Cetoprofeno 100 mg",
  "Cetoprofeno 150 mg LP",
  "Meloxicam 7,5 mg",
  "Meloxicam 15 mg",
  "Nimesulida 100 mg",
  "Piroxicam 20 mg",
  "Tenoxicam 20 mg",
  "Etoricoxibe 60 mg",
  "Celecoxibe 200 mg",

  // Antibióticos
  "Amoxicilina 500 mg",
  "Amoxicilina suspensão 250 mg/5 mL",
  "Amoxicilina + clavulanato 875/125 mg",
  "Amoxicilina + clavulanato 500/125 mg",
  "Ampicilina 500 mg",
  "Azitromicina 500 mg",
  "Azitromicina suspensão 200 mg/5 mL",
  "Cefalexina 500 mg",
  "Cefalexina suspensão 250 mg/5 mL",
  "Cefadroxil 500 mg",
  "Cefaclor 500 mg",
  "Cefuroxima 500 mg",
  "Ciprofloxacino 500 mg",
  "Ciprofloxacino 250 mg",
  "Norfloxacino 400 mg",
  "Levofloxacino 500 mg",
  "Levofloxacino 750 mg",
  "Doxiciclina 100 mg",
  "Tetraciclina 500 mg",
  "Eritromicina 500 mg",
  "Claritromicina 500 mg",
  "Metronidazol 250 mg",
  "Metronidazol 400 mg",
  "Metronidazol gel vaginal 100 mg",
  "Nitrofurantoína 100 mg",
  "Sulfametoxazol + trimetoprima 800/160 mg",
  "Sulfametoxazol + trimetoprima suspensão",
  "Clindamicina 300 mg",
  "Penicilina benzatina 1.200.000 UI",
  "Rifampicina 300 mg",

  // Antifúngicos / antivirais / antiparasitários
  "Fluconazol 150 mg",
  "Fluconazol 50 mg",
  "Itraconazol 100 mg",
  "Cetoconazol 200 mg",
  "Nistatina suspensão oral 100.000 UI/mL",
  "Terbinafina 250 mg",
  "Aciclovir 200 mg",
  "Aciclovir 400 mg",
  "Aciclovir 800 mg",
  "Valaciclovir 500 mg",
  "Oseltamivir 75 mg",
  "Mebendazol 100 mg",
  "Albendazol 400 mg",
  "Ivermectina 6 mg",
  "Metronidazol + nistatina creme vaginal",

  // Anti-hipertensivos
  "Losartana potássica 50 mg",
  "Losartana potássica 100 mg",
  "Valsartana 80 mg",
  "Valsartana 160 mg",
  "Olmesartana 40 mg",
  "Telmisartana 40 mg",
  "Telmisartana 80 mg",
  "Enalapril maleato 5 mg",
  "Enalapril maleato 10 mg",
  "Enalapril maleato 20 mg",
  "Captopril 25 mg",
  "Lisinopril 10 mg",
  "Ramipril 5 mg",
  "Anlodipino 5 mg",
  "Anlodipino 10 mg",
  "Nifedipino retard 20 mg",
  "Atenolol 25 mg",
  "Atenolol 50 mg",
  "Atenolol 100 mg",
  "Propranolol 40 mg",
  "Propranolol 80 mg",
  "Carvedilol 3,125 mg",
  "Carvedilol 6,25 mg",
  "Carvedilol 12,5 mg",
  "Carvedilol 25 mg",
  "Bisoprolol 5 mg",
  "Bisoprolol 10 mg",
  "Metoprolol succinato 25 mg",
  "Metoprolol succinato 50 mg",
  "Metoprolol succinato 100 mg",
  "Hidroclorotiazida 12,5 mg",
  "Hidroclorotiazida 25 mg",
  "Indapamida 1,5 mg",
  "Clortalidona 25 mg",
  "Furosemida 40 mg",
  "Espironolactona 25 mg",
  "Espironolactona 100 mg",
  "Hidralazina 25 mg",
  "Metildopa 250 mg",
  "Metildopa 500 mg",
  "Clonidina 0,150 mg",

  // Diabetes
  "Metformina 500 mg",
  "Metformina 850 mg",
  "Metformina 1000 mg",
  "Metformina XR 750 mg",
  "Glibenclamida 5 mg",
  "Gliclazida 30 mg MR",
  "Gliclazida 60 mg MR",
  "Glimepirida 2 mg",
  "Glimepirida 4 mg",
  "Empagliflozina 10 mg",
  "Empagliflozina 25 mg",
  "Dapagliflozina 10 mg",
  "Sitagliptina 50 mg",
  "Sitagliptina 100 mg",
  "Vildagliptina 50 mg",
  "Liraglutida 6 mg/mL",
  "Semaglutida injetável 1 mg",
  "Insulina NPH humana 100 UI/mL",
  "Insulina regular humana 100 UI/mL",
  "Insulina glargina 100 UI/mL",
  "Insulina lispro 100 UI/mL",
  "Insulina asparte 100 UI/mL",

  // Dislipidemia
  "Sinvastatina 10 mg",
  "Sinvastatina 20 mg",
  "Sinvastatina 40 mg",
  "Atorvastatina 10 mg",
  "Atorvastatina 20 mg",
  "Atorvastatina 40 mg",
  "Atorvastatina 80 mg",
  "Rosuvastatina 5 mg",
  "Rosuvastatina 10 mg",
  "Rosuvastatina 20 mg",
  "Rosuvastatina 40 mg",
  "Pravastatina 20 mg",
  "Ezetimiba 10 mg",
  "Fenofibrato 200 mg",
  "Ciprofibrato 100 mg",

  // Trato gastrointestinal
  "Omeprazol 20 mg",
  "Omeprazol 40 mg",
  "Pantoprazol 20 mg",
  "Pantoprazol 40 mg",
  "Esomeprazol 20 mg",
  "Esomeprazol 40 mg",
  "Lansoprazol 30 mg",
  "Rabeprazol 20 mg",
  "Ranitidina 150 mg",
  "Famotidina 40 mg",
  "Bromoprida 10 mg",
  "Metoclopramida 10 mg",
  "Domperidona 10 mg",
  "Ondansetrona 4 mg",
  "Ondansetrona 8 mg",
  "Hioscina 10 mg",
  "Hioscina + dipirona",
  "Loperamida 2 mg",
  "Simeticona 40 mg",
  "Simeticona gotas 75 mg/mL",
  "Bisacodil 5 mg",
  "Lactulose xarope",
  "Picossulfato de sódio gotas",
  "Polietilenoglicol sachê",
  "Sucralfato 1 g",
  "Pinaverium 100 mg",

  // Trato respiratório / alergias
  "Loratadina 10 mg",
  "Loratadina xarope 5 mg/5 mL",
  "Desloratadina 5 mg",
  "Cetirizina 10 mg",
  "Levocetirizina 5 mg",
  "Fexofenadina 60 mg",
  "Fexofenadina 120 mg",
  "Fexofenadina 180 mg",
  "Hidroxizina 25 mg",
  "Dexclorfeniramina 2 mg",
  "Salbutamol spray 100 mcg",
  "Salbutamol xarope 2 mg/5 mL",
  "Salbutamol solução para nebulização",
  "Fenoterol gotas",
  "Ipratrópio gotas",
  "Budesonida inalatória 200 mcg",
  "Budesonida inalatória 400 mcg",
  "Beclometasona inalatória 250 mcg",
  "Beclometasona spray nasal",
  "Mometasona spray nasal",
  "Formoterol + budesonida 6/200 mcg",
  "Formoterol + budesonida 12/400 mcg",
  "Salmeterol + fluticasona",
  "Tiotrópio brometo 18 mcg",
  "Montelucaste 10 mg",
  "Montelucaste 5 mg",
  "Prednisona 5 mg",
  "Prednisona 20 mg",
  "Prednisona 40 mg",
  "Prednisolona 5 mg/mL",
  "Dexametasona 4 mg",
  "Dexametasona 0,5 mg",
  "Betametasona injetável",
  "Hidrocortisona creme",
  "Acetilcisteína 600 mg",
  "Acetilcisteína xarope",
  "Bromexina xarope",
  "Carbocisteína xarope",

  // Saúde mental
  "Sertralina 25 mg",
  "Sertralina 50 mg",
  "Sertralina 100 mg",
  "Fluoxetina 10 mg",
  "Fluoxetina 20 mg",
  "Paroxetina 20 mg",
  "Citalopram 20 mg",
  "Citalopram 40 mg",
  "Escitalopram 10 mg",
  "Escitalopram 20 mg",
  "Venlafaxina 75 mg",
  "Venlafaxina 150 mg",
  "Duloxetina 30 mg",
  "Duloxetina 60 mg",
  "Mirtazapina 30 mg",
  "Mirtazapina 45 mg",
  "Bupropiona 150 mg",
  "Bupropiona 300 mg",
  "Trazodona 50 mg",
  "Trazodona 150 mg",
  "Amitriptilina 25 mg",
  "Amitriptilina 75 mg",
  "Nortriptilina 25 mg",
  "Nortriptilina 50 mg",
  "Clonazepam 0,5 mg",
  "Clonazepam 2 mg",
  "Diazepam 5 mg",
  "Diazepam 10 mg",
  "Lorazepam 1 mg",
  "Lorazepam 2 mg",
  "Alprazolam 0,25 mg",
  "Alprazolam 0,5 mg",
  "Alprazolam 1 mg",
  "Bromazepam 3 mg",
  "Bromazepam 6 mg",
  "Zolpidem 10 mg",
  "Zopiclona 7,5 mg",
  "Quetiapina 25 mg",
  "Quetiapina 100 mg",
  "Quetiapina 200 mg",
  "Risperidona 1 mg",
  "Risperidona 2 mg",
  "Olanzapina 5 mg",
  "Olanzapina 10 mg",
  "Aripiprazol 10 mg",
  "Haloperidol 5 mg",
  "Lítio carbonato 300 mg",
  "Valproato sódico 500 mg",
  "Topiramato 25 mg",
  "Topiramato 50 mg",
  "Lamotrigina 50 mg",
  "Lamotrigina 100 mg",
  "Carbamazepina 200 mg",
  "Carbamazepina 400 mg CR",
  "Fenitoína 100 mg",
  "Gabapentina 300 mg",
  "Pregabalina 75 mg",
  "Pregabalina 150 mg",

  // Tireoide
  "Levotiroxina sódica 25 mcg",
  "Levotiroxina sódica 50 mcg",
  "Levotiroxina sódica 75 mcg",
  "Levotiroxina sódica 88 mcg",
  "Levotiroxina sódica 100 mcg",
  "Levotiroxina sódica 112 mcg",
  "Levotiroxina sódica 125 mcg",
  "Levotiroxina sódica 150 mcg",
  "Metimazol 5 mg",
  "Propiltiouracila 100 mg",

  // Anticoagulantes / antiagregantes
  "Clopidogrel 75 mg",
  "Ticagrelor 90 mg",
  "Varfarina sódica 1 mg",
  "Varfarina sódica 5 mg",
  "Rivaroxabana 10 mg",
  "Rivaroxabana 15 mg",
  "Rivaroxabana 20 mg",
  "Apixabana 2,5 mg",
  "Apixabana 5 mg",
  "Dabigatrana 110 mg",
  "Dabigatrana 150 mg",
  "Enoxaparina 40 mg/0,4 mL",
  "Enoxaparina 60 mg/0,6 mL",

  // Urinário / Próstata
  "Tamsulosina 0,4 mg",
  "Doxazosina 2 mg",
  "Doxazosina 4 mg",
  "Finasterida 5 mg",
  "Dutasterida 0,5 mg",
  "Sildenafila 50 mg",
  "Tadalafila 5 mg",
  "Tadalafila 20 mg",
  "Oxibutinina 5 mg",
  "Solifenacina 5 mg",

  // Ginecologia / hormonal
  "Etinilestradiol + levonorgestrel",
  "Etinilestradiol + drospirenona",
  "Desogestrel 75 mcg",
  "Estradiol gel",
  "Tibolona 2,5 mg",
  "Norestisterona 10 mg",
  "Progesterona micronizada 200 mg",
  "Acetato de medroxiprogesterona injetável",
  "Levonorgestrel 1,5 mg (anticoncepção de emergência)",

  // Vitaminas / suplementos
  "Vitamina D3 1000 UI",
  "Vitamina D3 7000 UI",
  "Vitamina D3 50000 UI",
  "Vitamina B12 5000 mcg",
  "Vitamina C 500 mg",
  "Vitamina E 400 UI",
  "Sulfato ferroso 40 mg de ferro",
  "Sulfato ferroso xarope",
  "Sulfato de zinco 22 mg",
  "Cálcio carbonato 1250 mg",
  "Cálcio + vitamina D3",
  "Ácido fólico 5 mg",
  "Complexo B",
  "Cianocobalamina 5000 mcg",
  "Carbonato de cálcio 600 mg",
  "Glucosamina + condroitina",
  "Omega 3 1000 mg",
  "Magnésio dimalato",

  // Outros comuns
  "Alopurinol 100 mg",
  "Alopurinol 300 mg",
  "Colchicina 0,5 mg",
  "Diosmina + hesperidina 450/50 mg",
  "Cinarizina 75 mg",
  "Flunarizina 10 mg",
  "Betaistina 24 mg",
  "Dimenidrinato + piridoxina",
];

export const RENAME: DrugEntry[] = NAMES.map((name) => ({ name }));
